[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyetlx"
version = "0.1.0"
description = "Python bindings for the etlx Go library"
readme = "README.md"
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
authors = [
  { name="Real Data-Driven", email="real.datadriven@gmail.com" },
]

[project.urls]
Homepage = "https://github.com/realdatadriven/etlx"
"Bug Tracker" = "https://github.com/realdatadriven/etlx/issues"

#license = "MIT"
#license-files = ["LICEN[CS]E*"]

[tool.setuptools]
packages = ["src"]

[tool.extension]
name = "_etlx"
sources = ["src/_etlx.so", "src/etlx_go.so", "src/etlx_go.h", "src/etlx.c"]  # Replace with your shared object filename

[tool.setuptools.package-data]
"your_package_name" = [
    "*.so",
    "*.h",
    "*.c",
]


